---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/":
    get:
      summary: See the list of elements in MainPage
      tags:
      - All
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#components/schemas/root"
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
