---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/tests":
    post:
      summary: Creates a test
      tags:
      - Tests
      parameters: []
      responses:
        '201':
          description: Test created
          content:
            application/vnd.api+json:
              examples:
                Test created:
                  value:
                    data:
                      id: '029ba3ae-6eeb-4fcc-b802-a2d9e87ec462'
                      type: test
                      attributes:
                        test1: String
                        test2: 10
                        test3: false
                        test4: String 10 false
        '422':
          description: Invalid request
          content:
            application/vnd.api+json:
              examples:
                when test1 is missing:
                  value:
                    errors:
                    - status: unprocessable_entity
                      title: test1
                      detail: must be filled
                      source:
                        pointer: "/data/attributes/test1"
                when test2 is missing:
                  value:
                    errors:
                    - status: unprocessable_entity
                      title: test2
                      detail: must be filled
                      source:
                        pointer: "/data/attributes/test2"
                when test3 is missing:
                  value:
                    errors:
                    - status: unprocessable_entity
                      title: test3
                      detail: must be filled
                      source:
                        pointer: "/data/attributes/test3"
                when test2 is not an integer:
                  value:
                    errors:
                    - status: unprocessable_entity
                      title: test2
                      detail: must be an integer
                      source:
                        pointer: "/data/attributes/test2"
                when test3 is not a boolean:
                  value:
                    errors:
                    - status: unprocessable_entity
                      title: test3
                      detail: must be boolean
                      source:
                        pointer: "/data/attributes/test3"
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              "$ref": "#/components/schemas/new_test"
            examples:
              Test created:
                summary: Creates a test
                value:
                  data:
                    type: test
                    attributes:
                      test1: String
                      test2: 10
                      test3: false
              when test1 is missing:
                summary: Creates a test
                value:
                  data:
                    type: test
                    attributes:
                      test2: 10
                      test3: false
              when test2 is missing:
                summary: Creates a test
                value:
                  data:
                    type: test
                    attributes:
                      test1: String
                      test3: false
              when test3 is missing:
                summary: Creates a test
                value:
                  data:
                    type: test
                    attributes:
                      test1: String
                      test2: 10
              when test2 is not an integer:
                summary: Creates a test
                value:
                  data:
                    type: test
                    attributes:
                      test1: String
                      test2: not an integer
                      test3: false
              when test3 is not a boolean:
                summary: Creates a test
                value:
                  data:
                    type: test
                    attributes:
                      test1: String
                      test2: 10
                      test3: not a boolean
  "/tests/{id}":
    get:
      summary: Retrieves a test
      tags:
      - Tests
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/vnd.api+json:
              examples:
                OK:
                  value:
                    data:
                      id: 6facf42f-6fc7-44fd-9aa4-513cb7dbeadd
                      type: test
                      attributes:
                        test1: String with 20 chars
                        test2: 10
                        test3: true
                        test4: String with 20 chars 1000 true
              schema:
                "$ref": "#components/schemas/test"
        '404':
          description: Test not found
          content:
            application/vnd.api+json:
              examples:
                Test not found:
                  value:
                    errors:
                    - status: not_found
                      title: id
                      detail: not found
                      source:
                        pointer: "/data/attributes/id"
              schema:
                "$ref": "#/components/schemas/errors_object"
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
components:
  schemas:
    errors_object:
      type: object
      properties:
        errors:
          "$ref": "#/components/schemas/errors_array"
    errors_array:
      type: array
      properties:
        type: object
        properties:
          status:
            type: string
          title:
            type: string
          detail:
            type: string
          source:
            type: object
            properties:
              pointer:
                type: string
    test:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
            type:
              type: string
            attributes:
              type: object
              properties:
                test1:
                  type: string
                test2:
                  type: integer
                test3:
                  type: boolean
                test4:
                  type: string
              required:
              - test1
              - test2
              - test3
              - test4
          required:
          - id
          - type
          - attributes
      required:
      - data
    new_test:
      type: object
      properties:
        data:
          type: object
          properties:
            type:
              type: string
            attributes:
              type: object
              properties:
                test1:
                  type: string
                test2:
                  type: integer
                test3:
                  type: boolean
              required:
              - test1
              - test2
              - test3
          required:
          - type
          - attributes
      required:
      - data
